#!/bin/bash -e

result=$(kubectl -n "$KUBE_NAMESPACE" get secret production-secret -o json | jq .data.CODE | xargs echo | base64 -d)
if [[ "$result" != "$K8S_SECRET_CODE" ]]; then exit 1; fi

result=$(kubectl -n "$KUBE_NAMESPACE" get secret production-secret -o json | jq .data.CODE_MULTILINE | xargs echo | base64 -d)
if [[ "$result" != "$K8S_SECRET_CODE_MULTILINE" ]]; then exit 1; fi
